const app = require('express')();
const keyis='$#nasdfbsv0whjae0nASDVFDSsoi2ds#';
var SocketIOFileUpload5001=require("socketio-file-upload");var SocketIOFileUpload5002=require("socketio-file-upload");var SocketIOFileUpload5003=require("socketio-file-upload");var SocketIOFileUpload5004=require("socketio-file-upload");var SocketIOFileUpload5005=require("socketio-file-upload");var SocketIOFileUpload5006=require("socketio-file-upload");var SocketIOFileUpload5007=require("socketio-file-upload");var SocketIOFileUpload5008=require("socketio-file-upload");var SocketIOFileUpload5009=require("socketio-file-upload");var SocketIOFileUpload5010=require("socketio-file-upload");var SocketIOFileUpload5011=require("socketio-file-upload");var SocketIOFileUpload5012=require("socketio-file-upload");var SocketIOFileUpload5013=require("socketio-file-upload");var SocketIOFileUpload5014=require("socketio-file-upload");var SocketIOFileUpload5015=require("socketio-file-upload");var SocketIOFileUpload5016=require("socketio-file-upload");var SocketIOFileUpload5017=require("socketio-file-upload");var SocketIOFileUpload5018=require("socketio-file-upload");var SocketIOFileUpload5019=require("socketio-file-upload");var SocketIOFileUpload5020=require("socketio-file-upload");
function parallel(middlewares){return function(req,res,next){require('async').each(middlewares,function(mw,cb){mw(req,res,cb);},next);};}
app.use(parallel([SocketIOFileUpload5001.router,SocketIOFileUpload5002.router,SocketIOFileUpload5003.router,SocketIOFileUpload5004.router,SocketIOFileUpload5005.router,SocketIOFileUpload5006.router,SocketIOFileUpload5007.router,SocketIOFileUpload5008.router,SocketIOFileUpload5009.router,SocketIOFileUpload5010.router,SocketIOFileUpload5011.router,SocketIOFileUpload5012.router,SocketIOFileUpload5013.router,SocketIOFileUpload5014.router,SocketIOFileUpload5015.router,SocketIOFileUpload5016.router,SocketIOFileUpload5017.router,SocketIOFileUpload5018.router,SocketIOFileUpload5019.router,SocketIOFileUpload5020.router,require('compression')(),require('./router'),require('cors')(),require('body-parser').json(),require('body-parser').urlencoded({extended:false}),require('passport').initialize(),require('request-ip').mw(),require('cookie-parser')(keyis),require('cookie-encrypter')(keyis)]));
const IOFileFunction =require('./ioConnect');const ssl={key:require('fs').readFileSync('c:/nginx/conf/chattank.key'),cert:require('fs').readFileSync('c:/nginx/conf/chattank.crt')};
const server1=require('https').createServer(ssl,app).listen(2001);const serverio1=require('https').createServer(ssl,app).listen(5001);SocketIOFileUpload5001.listen(serverio1);const io1=require('socket.io')(serverio1,{origins:'*:*',transports:['websocket','polling']});app.set('socketio1',io1);IOFileFunction(io1,5001,SocketIOFileUpload5001,socketConnect,socketDisConnect,app);
const server2=require('https').createServer(ssl,app).listen(2002);const serverio2=require('https').createServer(ssl,app).listen(5002);SocketIOFileUpload5002.listen(serverio2);const io2=require('socket.io')(serverio2,{origins:'*:*',transports:['websocket','polling']});app.set('socketio2',io2);IOFileFunction(io2,5002,SocketIOFileUpload5002,socketConnect,socketDisConnect,app);
const server3=require('https').createServer(ssl,app).listen(2003);const serverio3=require('https').createServer(ssl,app).listen(5003);SocketIOFileUpload5003.listen(serverio3);const io3=require('socket.io')(serverio3,{origins:'*:*',transports:['websocket','polling']});app.set('socketio3',io3);IOFileFunction(io3,5003,SocketIOFileUpload5003,socketConnect,socketDisConnect,app);
const server4=require('https').createServer(ssl,app).listen(2004);const serverio4=require('https').createServer(ssl,app).listen(5004);SocketIOFileUpload5004.listen(serverio4);const io4=require('socket.io')(serverio4,{origins:'*:*',transports:['websocket','polling']});app.set('socketio4',io4);IOFileFunction(io4,5004,SocketIOFileUpload5004,socketConnect,socketDisConnect,app);
const server5=require('https').createServer(ssl,app).listen(2005);const serverio5=require('https').createServer(ssl,app).listen(5005);SocketIOFileUpload5005.listen(serverio5);const io5=require('socket.io')(serverio5,{origins:'*:*',transports:['websocket','polling']});app.set('socketio5',io5);IOFileFunction(io5,5005,SocketIOFileUpload5005,socketConnect,socketDisConnect,app);
const server6=require('https').createServer(ssl,app).listen(2006);const serverio6=require('https').createServer(ssl,app).listen(5006);SocketIOFileUpload5006.listen(serverio6);const io6=require('socket.io')(serverio6,{origins:'*:*',transports:['websocket','polling']});app.set('socketio6',io6);IOFileFunction(io6,5006,SocketIOFileUpload5006,socketConnect,socketDisConnect,app);
const server7=require('https').createServer(ssl,app).listen(2007);const serverio7=require('https').createServer(ssl,app).listen(5007);SocketIOFileUpload5007.listen(serverio7);const io7=require('socket.io')(serverio7,{origins:'*:*',transports:['websocket','polling']});app.set('socketio7',io7);IOFileFunction(io7,5007,SocketIOFileUpload5007,socketConnect,socketDisConnect,app);
const server8=require('https').createServer(ssl,app).listen(2008);const serverio8=require('https').createServer(ssl,app).listen(5008);SocketIOFileUpload5008.listen(serverio8);const io8=require('socket.io')(serverio8,{origins:'*:*',transports:['websocket','polling']});app.set('socketio8',io8);IOFileFunction(io8,5008,SocketIOFileUpload5008,socketConnect,socketDisConnect,app);
const server9=require('https').createServer(ssl,app).listen(2009);const serverio9=require('https').createServer(ssl,app).listen(5009);SocketIOFileUpload5009.listen(serverio9);const io9=require('socket.io')(serverio9,{origins:'*:*',transports:['websocket','polling']});app.set('socketio9',io9);IOFileFunction(io9,5009,SocketIOFileUpload5009,socketConnect,socketDisConnect,app);
const server10=require('https').createServer(ssl,app).listen(2010);const serverio10=require('https').createServer(ssl,app).listen(5010);SocketIOFileUpload5010.listen(serverio10);const io10=require('socket.io')(serverio10,{origins:'*:*',transports:['websocket','polling']});app.set('socketio10',io10);IOFileFunction(io10,5010,SocketIOFileUpload5010,socketConnect,socketDisConnect,app);
const server11=require('https').createServer(ssl,app).listen(2011);const serverio11=require('https').createServer(ssl,app).listen(5011);SocketIOFileUpload5011.listen(serverio11);const io11=require('socket.io')(serverio11,{origins:'*:*',transports:['websocket','polling']});app.set('socketio11',io11);IOFileFunction(io11,5011,SocketIOFileUpload5011,socketConnect,socketDisConnect,app);
const server12=require('https').createServer(ssl,app).listen(2012);const serverio12=require('https').createServer(ssl,app).listen(5012);SocketIOFileUpload5012.listen(serverio12);const io12=require('socket.io')(serverio12,{origins:'*:*',transports:['websocket','polling']});app.set('socketio12',io12);IOFileFunction(io12,5012,SocketIOFileUpload5012,socketConnect,socketDisConnect,app);
const server13=require('https').createServer(ssl,app).listen(2013);const serverio13=require('https').createServer(ssl,app).listen(5013);SocketIOFileUpload5013.listen(serverio13);const io13=require('socket.io')(serverio13,{origins:'*:*',transports:['websocket','polling']});app.set('socketio13',io13);IOFileFunction(io13,5013,SocketIOFileUpload5013,socketConnect,socketDisConnect,app);
const server14=require('https').createServer(ssl,app).listen(2014);const serverio14=require('https').createServer(ssl,app).listen(5014);SocketIOFileUpload5014.listen(serverio14);const io14=require('socket.io')(serverio14,{origins:'*:*',transports:['websocket','polling']});app.set('socketio14',io14);IOFileFunction(io14,5014,SocketIOFileUpload5014,socketConnect,socketDisConnect,app);
const server15=require('https').createServer(ssl,app).listen(2015);const serverio15=require('https').createServer(ssl,app).listen(5015);SocketIOFileUpload5015.listen(serverio15);const io15=require('socket.io')(serverio15,{origins:'*:*',transports:['websocket','polling']});app.set('socketio15',io15);IOFileFunction(io15,5015,SocketIOFileUpload5015,socketConnect,socketDisConnect,app);
const server16=require('https').createServer(ssl,app).listen(2016);const serverio16=require('https').createServer(ssl,app).listen(5016);SocketIOFileUpload5016.listen(serverio16);const io16=require('socket.io')(serverio16,{origins:'*:*',transports:['websocket','polling']});app.set('socketio16',io16);IOFileFunction(io16,5016,SocketIOFileUpload5016,socketConnect,socketDisConnect,app);
const server17=require('https').createServer(ssl,app).listen(2017);const serverio17=require('https').createServer(ssl,app).listen(5017);SocketIOFileUpload5017.listen(serverio17);const io17=require('socket.io')(serverio17,{origins:'*:*',transports:['websocket','polling']});app.set('socketio17',io17);IOFileFunction(io17,5017,SocketIOFileUpload5017,socketConnect,socketDisConnect,app);
const server18=require('https').createServer(ssl,app).listen(2018);const serverio18=require('https').createServer(ssl,app).listen(5018);SocketIOFileUpload5018.listen(serverio18);const io18=require('socket.io')(serverio18,{origins:'*:*',transports:['websocket','polling']});app.set('socketio18',io18);IOFileFunction(io18,5018,SocketIOFileUpload5018,socketConnect,socketDisConnect,app);
const server19=require('https').createServer(ssl,app).listen(2019);const serverio19=require('https').createServer(ssl,app).listen(5019);SocketIOFileUpload5019.listen(serverio19);const io19=require('socket.io')(serverio19,{origins:'*:*',transports:['websocket','polling']});app.set('socketio19',io19);IOFileFunction(io19,5019,SocketIOFileUpload5019,socketConnect,socketDisConnect,app);
const server20=require('https').createServer(ssl,app).listen(2020);const serverio20=require('https').createServer(ssl,app).listen(5020);SocketIOFileUpload5020.listen(serverio20);const io20=require('socket.io')(serverio20,{origins:'*:*',transports:['websocket','polling']});app.set('socketio20',io20);IOFileFunction(io20,5020,SocketIOFileUpload5020,socketConnect,socketDisConnect,app);
function socketConnect(socket){
  //socket.removeListener('mediainfo',function(){});socket.on('mediainfo',function(data){socket.disconnect();});
}
function socketDisConnect(socket){
  //socket.removeListener('mediainfo',function(){});
}
app.get('/', (req,res) => {
  res.sendFile(require('path').join(__dirname, '../client/build', 'index.html'));
});
app.get('/:id', (req,res) => {
  let dirPath = 'c:\/nginx\/html\/app\/client\/src\/components'+require('url').parse(req.url).pathname;
  if(require('fs').existsSync(dirPath) && require('fs').lstatSync(dirPath).isDirectory()){
    res.sendFile(require('path').join(__dirname, '../client/build', 'index.html'));
  }
});
app.use(require('serve-static')('c:\/nginx\/html\/app\/client\/build\/',{maxAge:86400000}));//display public build